services:
  db:
    image: postgres:15.8
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: users_db
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - go_network

  postgres_kc:
    image: postgres:15.3
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    ports:
      - 5433:5432
    volumes:
      - db-data-kc:/var/lib/postgresql/data
    networks:
      - go_network

  keycloak:
    image: keycloak/keycloak:22.0.5
    environment:
      KC_DB: postgres
      KC_DB_SCHEMA: public
      KC_DB_URL_DATABASE: keycloak
      KC_DB_URL_HOST: postgres_kc
      KC_DB_URL_PORT: 5432
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HOSTNAME_STRICT: "false"
      #KC_LOG_LEVEL: DEBUG
    ports:
      - 7080:8080
    entrypoint: /opt/keycloak/bin/kc.sh start-dev --import-realm
    volumes:
      - ./keycloak/import:/opt/keycloak/data/import
    depends_on:
      - postgres_kc
    networks:
      - go_network


volumes:
  db-data:
  db-data-kc:

networks:
  go_network:
